### ISSUE TITLE
Vector4 is different from imvec4

### ISSUE THREAD

**Issue by AhmedZero** [InfectedLibraries/InfectedImGui#2]
order of vector4 is different from imvec4
```c++
struct ImVec4
{
    float                                                     x, y, z, w;
    constexpr ImVec4()                                        : x(0.0f), y(0.0f), z(0.0f), w(0.0f) { }
    constexpr ImVec4(float _x, float _y, float _z, float _w)  : x(_x), y(_y), z(_z), w(_w) { }
#ifdef IM_VEC4_CLASS_EXTRA
    IM_VEC4_CLASS_EXTRA     // Define additional constructors and implicit cast operators in imconfig.h to convert back and forth between your math types and ImVec4.
#endif
};
```
```C#
 public struct Vector4 : IEquatable<Vector4>, IFormattable
    {
        public float W;

        public float X;

        public float Y;

        public float Z;
}
```

**Comment by PathogenDavid** [comment]
I assume you closed [since they are in fact the same layout](https://github.com/dotnet/runtime/blob/f2ce5e853e9a18f638ae54dd09078c9f8e0a200a/src/libraries/System.Private.CoreLib/src/System/Numerics/Vector4.cs#L21-L31), but thanks for double-checking me!

Out of curiosity, what were you looking at that showed `W` coming first?

Also FYI, I just published [v0.0.1](https://github.com/MochiLibraries/Mochi.DearImGui/releases/tag/v0.0.1), which greatly improves how C++ references on Dear ImGui's API surface are exposed in C#.

**Comment by AhmedZero** [comment]
In my VS 2022, I think it's a VS problem, it's ordered the fields by alphabetical not by layout struct.

**Comment by PathogenDavid** [comment]
Ah yeah, I forgot the metadata view did that. You might consider [enabling navigation to decompiled sources](https://docs.microsoft.com/en-US/visualstudio/ide/go-to-and-peek-definition?view=vs-2022#view-decompiled-source-definitions-instead-of-metadata-c). It's quite a bit more useful most of the time.
